dataset_name: default
dataset_path: TheFinAI/XBRL_Tagging_Pipeline_DeepSeek_v3_Rerank_1
output_type: generate_until
doc_to_target: '{{answer}}'
doc_to_text: '{{query}}'
fewshot_split: test
should_decontaminate: true
doc_to_decontamination_query: "{{query}}"
generation_kwargs:
  until:
    - "JSON_END"
  do_sample: false
  temperature: 0.0
  max_gen_toks: 1024
metric_list:
  - metric: exact_match
    aggregation: mean
    higher_is_better: true
metadata:
  version: '1.0'
task: DeepSeekV3_NEN
tag: xbrl
test_split: test
