dataset_name: default
dataset_path: ChanceFocus/flare-sm-acl
output_type: generate_until
doc_to_target: '{{answer}}'
doc_to_text: '{{query}}'
fewshot_split: test
should_decontaminate: true
doc_to_decontamination_query: "{{query}}"
generation_kwargs:
  until:
    - "."
    - ","
  do_sample: false
  temperature: 0.0
  max_gen_toks: 30
filter_list:
  - name: "score-first"
    filter:
      - function: "regex"
        regex_pattern: "(Rise|Fall)"
      - function: "take_first"
metric_list:
  - metric: mcc
    higher_is_better: true
metadata:
  version: '1.0'
task: ACL18gen
tag: en_gen
test_split: test