dataset_name: default
dataset_path: ChanceFocus/flare-ectsum
output_type: generate_until
doc_to_target: '{{ {"label": label, "text": text} | tojson }}'
doc_to_text: '{{query}}'
fewshot_split: test
should_decontaminate: true
doc_to_decontamination_query: "{{query}}"
generation_kwargs:
  until:
    - "@@"
  do_sample: false
  temperature: 0.0
  max_gen_toks: 512
metric_list:
  - metric: !function multifin_utils.ect_rouge1
    aggregation: !function multifin_utils.ect_rouge1_agg
    higher_is_better: true
metadata:
  version: '1.0'
task: ECTSUM
tag: en
test_split: test